/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as MmaTyFb1RouteImport } from './routes/mma-ty-fb1'
import { Route as MmaFb1RouteImport } from './routes/mma-fb1'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const MmaTyFb1Route = MmaTyFb1RouteImport.update({
  id: '/mma-ty-fb1',
  path: '/mma-ty-fb1',
  getParentRoute: () => rootRouteImport,
} as any)
const MmaFb1Route = MmaFb1RouteImport.update({
  id: '/mma-fb1',
  path: '/mma-fb1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mma-fb1': typeof MmaFb1Route
  '/mma-ty-fb1': typeof MmaTyFb1Route
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mma-fb1': typeof MmaFb1Route
  '/mma-ty-fb1': typeof MmaTyFb1Route
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mma-fb1': typeof MmaFb1Route
  '/mma-ty-fb1': typeof MmaTyFb1Route
  '/thank-you': typeof ThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mma-fb1' | '/mma-ty-fb1' | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mma-fb1' | '/mma-ty-fb1' | '/thank-you'
  id: '__root__' | '/' | '/mma-fb1' | '/mma-ty-fb1' | '/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MmaFb1Route: typeof MmaFb1Route
  MmaTyFb1Route: typeof MmaTyFb1Route
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mma-ty-fb1': {
      id: '/mma-ty-fb1'
      path: '/mma-ty-fb1'
      fullPath: '/mma-ty-fb1'
      preLoaderRoute: typeof MmaTyFb1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mma-fb1': {
      id: '/mma-fb1'
      path: '/mma-fb1'
      fullPath: '/mma-fb1'
      preLoaderRoute: typeof MmaFb1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MmaFb1Route: MmaFb1Route,
  MmaTyFb1Route: MmaTyFb1Route,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
